# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User: bcrypt
        
    access_control:
#        - { path: ^/new, roles: ROLE_USER }


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        ours_database_users:
            entity: 
                class: UserBundle:User
            

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            anonymous: ~
        
           
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path: logout
                target: event_index
                
      
            
          
            
         


         