<?php

namespace UserBundle\Repository;

use \Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface {

    /**
     * 
     * @param $username
     * @return User|null
     */
    public function findOneByUsernameOrEmail($username) {
        return $this->createQueryBuilder('u')
                        ->andWhere('u.username = :username OR u.email = :email')
                        ->setParameter('username', $username)
                        ->setParameter('email', $username)
                        ->getQuery()
                        ->getOneOrNullResult();
    }

    public function loadUserByUsername($username) {
        $user = $this->findOneByUsernameOrEmail($username);

        if (!$user) {
            throw new UsernameNotFoundException("WRONG! no user found for" . $username);
        }

        return $user;
    }



}
